### ISSUE TITLE
[Chore] 라이브러리 추가 및 Gradle 설정

### ISSUE THREAD

**Issue by Zzu-h** [Zzu-h/ArtWhale#1]
### 📌 내용
프로젝트 사용할 라이브러리 추가 및 필요한 Gradle 설정

### 🛠 ToDo
- [x] Hilt 의존성 추가
- [x] Network 의존성 추가
- [x] Glide 의존성 추가
- [x] viewModels 종속성 추가
- [x] DataBinding 추가
- [x] git ignore 설정 추가
- [x] dependency version 관리를 위한 추출
