### ISSUE TITLE
[Feat] Home-Music 기능 구현

### ISSUE THREAD

**Issue by Zzu-h** [Zzu-h/ArtWhale#15]
### 📌 내용
구성된 화면들에 기능을 추가한다.
데이터 로드 및 각 버튼 기능 구현

### 🛠 ToDo
- [x] 데이터를 로드하고 rv에 전달 및 표시
- [ ] 각 버튼에 따른 화면 이동 구현
- [ ] 앱바 기능 구현

**Comment by Zzu-h** [comment]
각 화면 이동에 관해서는 다른 화면을 만들고 난 후에 연결예정
