### ISSUE TITLE
[Feat] Home-Profile 화면 구성하기

### ISSUE THREAD

**Issue by Zzu-h** [Zzu-h/ArtWhale#22]
### 📌 내용
프로필 기능 구현

### 🛠 ToDo
- [ ] 수정 모드 전환 시 블러 표시
- [ ] 좋아요 삭제 기능 (Cache)
- [ ] 수정 결과 적용
- [ ] 이미지 갤러리에서 받아오기
- [ ] 화면 이동 --- (다른 화면 구현했을 때 적용 예정)
