### ISSUE TITLE
[UI] Music Play 화면 구현하기 Feat. Bottom Sheet

### ISSUE THREAD

**Issue by Zzu-h** [Zzu-h/ArtWhale#29]
### 📌 내용
Main 화면에 Bottom Sheet화면을 추가하고, 음악 화면 fragment를 만든다.

### 🛠 ToDo
- [x] MainActivity.xml -> BottomSheet 추가
- [x] MusicPlayer 화면 구현
- [x] 각종 아이콘 추가
  - player_stop
  - player_play
  - player_prev
  - player_next
