### ISSUE TITLE
[Refactor] 전반적인 UI 리팩토링

### ISSUE THREAD

**Issue by Zzu-h** [Zzu-h/ArtWhale#35]
### 📌 내용
UI 수정

### 🛠 ToDo
- [x] text size 축소
- [x] Appbar UI 수정
- [x] album like icon 추가
