### ISSUE TITLE
[UI] Register 화면 구현

### ISSUE THREAD

**Issue by Zzu-h** [Zzu-h/ArtWhale#37]
### 📌 내용
Album Register 및 Music Register 화면 구현하기

### 🛠 ToDo
- [x] Album Register 화면 구현
- [x] Music Register 화면 구현하기
- [x] Music Register - AI & Normal 버전 화면 구현하기
- [x] Music Register - Image List 화면 구현하기
- [x] Music Register Mini Player 화면 구현하기
