### ISSUE TITLE
[Feat] Register 화면 기능 구현하기

### ISSUE THREAD

**Issue by Zzu-h** [Zzu-h/ArtWhale#38]
### 📌 내용
Album Register 및 Music Register 화면 구현하기

### 🛠 ToDo
- Album
  - [x] 이미지 로드하기
  - [x] 스피너 등록 - 감정 리스트 받아오기
  - [x] 각 버튼 기능 구현
- Music
  - [x] 음원 로컬에서 로드하기
    - [x] 로드 후 미니플레이어 보여주기
    - [x] 로드 후 버튼 활성화
  - [x] 각 버튼 기능 구현
  - [x] ai 모드인지 체크 후 전체 UI 변경
  - [x] 스피너 등록 - 감정 리스트 받아오기
