### ISSUE TITLE
[Feat] Search 기능 구현

### ISSUE THREAD

**Issue by Zzu-h** [Zzu-h/ArtWhale#51]
### 📌 내용
검색 기능을 구현한다.

### 🛠 ToDo
- [x] 최근 검색 이력을 RoomDB로 저장한다.
- [x] 검색된 데이터를 화면에 띄운다.
- [x] 검색 입력 창 포커스가 되어있을 때 최근 이력을 보여준다.
  - 포커스가 없을 땐 보여주지 않음
