### ISSUE TITLE
[Feat] 데이터 불러오기 (Network 연결)

### ISSUE THREAD

**Issue by Zzu-h** [Zzu-h/ArtWhale#59]
### 📌 내용
데이터 불러오기 (Network 연결)

### 🛠 ToDo
- [x] Notice List 불러오기
- [x] Music List 불러오기
  - Music Chart
  - New Music
- [x] Album List 불러오기
  - Top Albums
  - All Albums
