### ISSUE TITLE
[Chore] 버전 1.1 배포

### ISSUE THREAD

**Issue by Zzu-h** [Zzu-h/ArtWhale#67]
### 📌 변경사항
- Mini Player 구현
- Register Player 기능 구현
- Ai Album Register Image Select 구현

### 🛠 ToDo
- [ ] Mini Player 구현
- [ ] Register Player 기능 구현
- [x] Ai Album Register Image Select 구현
