### ISSUE TITLE
[feat] Data Layer (& Domain Layer) 세부 구현

### ISSUE THREAD

**Issue by Zzu-h** [Zzu-h/ArtWhale#69]
### 📌 내용
각 레이어의 세부 기능을 구현한다.
유닛 테스트를 통해 적절히 동작하는지를 확인한다.

### 🛠 ToDo
- [x] UseCase 작성
- [x] Repository & DataSource 작성
- [x] 각 기능이 적절히 동작하는지 Unit Test Code 작성
- [x] Retrofit2를 활용 및 네트워크 연결
